version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /python-app/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /python-app/docker-credentials/password
    DOCKER_REGISTRY_URL: /python-app/docker-registry/url  # e.g., 1234567890.dkr.ecr.us-east-1.amazonaws.com
    IMAGE_NAME: /python-app/image-name # e.g., my-python-app

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - cd simple-python-app
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo "Running tests..."
      - cd simple-python-app  # Change directory before running tests!
      - python -m unittest discover
  build:
    commands:
      - echo "Building Docker image..."
      - cd simple-python-app  # Change to the directory containing Dockerfile
      - docker login -u "$DOCKER_REGISTRY_USERNAME" -p "$DOCKER_REGISTRY_PASSWORD" "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/$IMAGE_NAME:latest" . # The "." is crucial!
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/$IMAGE_NAME:latest"
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'  # Package everything within simple-python-app
  base-directory: simple-python-app # Correct base directory
