version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /python-app/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /python-app/docker-credentials/password
    DOCKER_REGISTRY_URL: /python-app/docker-registry/url
    IMAGE_NAME: /python-app  # Make the image name configurable

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - cd simple-python-app  # Change directory *before* installing dependencies
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo "Running tests..."
      - python -m unittest discover # Run tests
  build:
    commands:
      - echo "Building Docker image..."
      - docker login -u "$DOCKER_REGISTRY_USERNAME" -p "$DOCKER_REGISTRY_PASSWORD" "$DOCKER_REGISTRY_URL" # Log in!
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/python-app:latest" .
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/python-app:latest"
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*' # Package everything within simple-python-app
  base-directory: simple-python-app # Correct base directory
